package submenu;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Administrator
 */
public class AboutDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form AboutOkDialog
     */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        homepageLinkLabel = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        rooibos_logoLabel = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(541, 637));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("E-mail : info@teasofts.com");

        homepageLinkLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        homepageLinkLabel.setForeground(new java.awt.Color(51, 153, 255));
        homepageLinkLabel.setText("<HTML><U>http://www.teasofts.com</U></HTML>");
        homepageLinkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homepageLinkLabelMouseClicked(evt);
            }
        });

        label10.setFont(new java.awt.Font("굴림체", 0, 12)); // NOI18N
        label10.setText("이 프로그램은 전북대학교병원 임상시험 글로벌선도센터의 후원으로 제작되었습니다.");

        rooibos_logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPackage/Rooibos_logo128.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel28.setText("Rooibos 2.1.5.Kor @ TEA SOFTs");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GNU General Public Licence", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("본 소프트웨어는 TEASOFTs와 협의가된 사용자만이 사용이 가능하며 무료로 배포하거나 돈을 받고 배포하는 것은 불법입니다. 소프트웨어의 해킹 및 임의로 변경하는 것은 금지합니다. 커머셜 사용자나 변경이 필요한 경우에는 제작자에게 연락하여 주십시오.\n----------------------------------------------------------------\n본 소프트웨어 최종사용자 사용권 계약서(이하 \"사용권 계약서\")는 TEASOFTs (이하 \"회사\") 및 협력사가 개발, 판매, 배포한 소프트웨어 제품에 대해 개인  또는 단일 업체(이하 \"사용자\")와 \"회사\" 간에 체결하는 사용 계약입니다. 본 \"사용권 계약서\"에 해당하는 소프트웨어는 TEASOFTs 홈페이지 (http://www.teasofts.com)에서 제공되는 소프트웨어의 전체 버전 입니다. 본 \"회사\"의 소프트웨어(이하 \"제품\")에는 컴퓨터 소프트웨어 뿐만 아니라, \"제품\"에 부속된 자료, 매체, 파일, 데이터, 인쇄물 및 \"온라인\" 또는 전자문서(\"소프트웨어\") 등이 포함될 수 있습니다.\n\"사용자\"는 본 \"제품\"의 전부 또는 일부를 컴퓨터 또는 네트워크 상에서 설치, 복사하거나 실행함으로써 본 \"사용권 계약서\" 내용에 동의하고 사용하는 것으로 간주됩니다.\"사용자\"가 본 \"사용권 계약서\" 내용에 동의하지 않을 경우에는 \"제품\"을 사용 할 수 없습니다.\n\n\"회사\"는 합리적인 사유가 발생될 경우에는 이 \"사용권 계약서\"를 변경 할 수 있으며, \"사용권 계약서\"를 변경 할 경우에는 지체 없이 이를 사전에 공시합니다. 이 \"사용권 계약서\"에 동의하는 것은 정기적으로 \"제품\" 홈페이지를 방문하여 \"사용권 계약서\"의 변경사항을 확인하는 것에 동의함을 의미하며, 변경된 약관에 대한 정보를 알지 못해 발생하는 사용자의 피해는 회사에서 책임지지 않습니다. \n\n제1조 (사용 허가)\n  1항. 본 \"사용권 계약서\"에 동의하는 경우 \"사용자\"에게 다음과 같은 권리가 허가 됩니다.\n  2항. TEASOFTs \"제품\"은 정당하게 구매한 \"사용자\"에게 사용할 권리를 허용하며, 비영리 단체 또는 개인의 경우에 한하여 아카데믹 버젼을  소정의 제한을 가지고 사용할 권리를 허용합니다.\n  3항. \"사용자\"는 \"제품\"을 정당하게 사용하기 위하여, 본 \"제품\"을 다운로드 하거나 복사 할 수 있으며, 백업이나 보관용으로 본 \"제품\"의 복사본을 만들 수 있습니다.\n\n제2조 (저작권 및 용도 제한)\n  1항. \"제품\"의 모든 정품 및 복사본에는 저작권 정보가 표시되어야 합니다.\n  2항. \"제품\"과 \"제품\"에 포함된 모든 부속물, 부속 인쇄물, 품명 및 소프트웨어의 복사본들에 대한 저작권과 지적 소유권은 회사와 협력사가 소유하고 있습니다. “회사”는 그러한 소유권과 지적 재산권을 인정하고, “회사” 또는 협력사의 “제품”에 관한 소유권 또는 권리를 위태롭게 하거나 제한 혹은 방해할 어떠한 행동도 취하지 않을 것입니다. 이 권리와 “제품”은 대한민국의 법률,저작권, 다른 지적 재산권법 그리고 국제 저작권 조약에 의하여 보호됩니다.\n  3항. \"사용자\"는 \"제품\"의 사용과 관련하여 대한민국 저작권법, 국제 저작권 조약 및 기타 관련 법률을 준수해야 하며, 관련 법규에서 명시적으로 허용한 제한적인 범위 이외에 \"제품\"을 리버스엔지니어링, 디컴파일, 디스어셈블, 재패키징, 타 프로그램과의 동시설치 할 수 없으며, \"제품\"의 구성 요소 전체 혹은 일부를 복사하거나 변형, 개작 할 수 없고, 또한 \"회사\"의 사전 승인 없이 임의로 \"제품\" 및 관련 인쇄물을 복제 혹은 복사하여 배포 할 수 없습니다.\n  4항. \"사용자\"가 ‘제2조 3항’의 행위로 \"회사\"의 저작권을 침해하여 손해가 발생한 경우에 \"회사\"는 최종 \"사용자\"에게 저작권의 침해로 인한 모든 손해에 대한 배상을 청구 할 수 있습니다.\n  5항. \"회사\"는 \"제품\"의 저작권, 유통권, 배포권, 전시권, 공표권, 성명표시권,복제권, 개작권, 전송권 및 영업권 등의 권리를 소유하고 있는 바, 위 권리를 침해한 자는 손해배상 및 형사상 책임을 부담해야 합니다.\n\n제3조 (소프트웨어 재 배포 관련)\n  1항. \"제품\"은 \"회사\"의 공식 홈페이지(http://www.teasofts.com)에서 최신버전의 \"제품\"을 다운로드 받아 재배포 할 수 있습니다.\n  2항. \"제품\"은 반드시 설치 파일의 변경/변형 없이 배포하여야 하며, \"제품\"을 리버스엔지니어링, 디컴파일, 디스어셈블, 재패키징, 타 프로그램과의 동시설치를 할 수 없으며, \"제품\"의 구성 요소 전체 혹은 일부를 복사하거나 변경, 개작할 수 없습니다.\n  3항. 허가된 목적이나 용도 이외에 상업적/비상업적 용도로 재 배포하는 과정에서 재 배포 당사자의 유/무형상의 이익 취득에 활용되거나 이와 유사한 것으로 간주되는 경우 또는 \"회사\"의 사업 정책에 위반되는 경우에는 재 배포 허가를 즉시 철회 할 수 있습니다.\n  4항. \"회사\"의 허락 없이 사용자 유입을 위해 검색엔진의 키워드 광고로 \"제품\"을 이용하거나, \"제품\"명 및 \"회사\"명과 유사, 동일한 이름의 도메인, 사이트, 블로그, 카페 등을 사용하여 재 배포하거나, 기타 상업적 목적으로 재 배포 하는 경우, 이로 인한 일체의 민/형사상 책임을 부담하여야 합니다.\n  5항. \"회사\"가 허락한 재 배포의 경우라도, 허락 받은 당사자가 허락된 목적 내지 용도 이외의 방법으로 재 배포 할 경우 \"회사\"는 언제든지 재 배포 허락을 철수 할 수 있으며, 허락 받은 당사자는 이로 인한 책임을 부담 할 수 있습니다.\n\n제4조 (결과적 손해에 대한 책임의 문제)\n  1항. \"제품\"의 사용에 대한 결과는 전적으로 \"사용자\"의 책임 하에 있으며, \"사용자\"의 \"제품\" 사용 목적에 대한 적합성, 품질 등에 대한 책임은 \"사용자\"의 몫입니다.\n  2항. \"회사\"에서 본 \"제품\"을 사용 할 수 없거나 사용법을 제대로 인식하지 못해서 발생한 이익 손실, 업무 중단, 사업 정보의 손실 또는 금전상의 손실 등 사업상의 손해를 포함한 부수적이고 간접적인 손해에 대해서 비록 이와 같은 손해 가능성에 대해 사전에 알고 있었다고 해도 관련 법규에서 허용하는 최대 범위 내에서 책임을 지지 않습니다.\n  3항. 본 \"제품\"을 구매한 \"사용자\"에게 \"회사\"가 부담하는 책임은 \"회사\"의 고의가 없는 한 \"사용자\"가 \"제품\"에 대한 사용권을 취득하기 위해 실제로 지급한 비용을 초과하지 않습니다.\n  4항. 관할권에 따라서는 위와 같은 결과적이거나 부수적인 손해에 대한 책임을 배제하거나 제한하지 못하도록 하는 경우가 있으므로, 위의 제한 사항이 \"사용자\"에게 적용되지 않을 수도 있습니다.\n\n제5조 (계약의 인정)\n  \"사용자\"는 \"사용권 계약서\"에 명시된 모든 내용을 읽고 이해하여, 계약서 조건에 동의 할 것을 인정합니다. \n\n제6조 (계약서의 종료 및 해지)\n  1항. \"사용자\"가 본 \"사용권 계약서\"의 내용을 준수하지 않는 경우, \"회사\"는 여타 권리를 침해하지 않고 계약서를 종료 할 수 있습니다.\n  2항 \"사용자\"가 개정된 약관에 동의하지 않을 경우, \"제품\"을 삭제함으로써 본 이용계약을 해지 할 수 있습니다.\n\n제7조 (계약에 대한 문의 사항)  \n  \"제품\"을 사용하기 위한 라이선스 구입 및 \"사용권 계약서\"에 대한 의문 사항은 연락처를 참고하시기 바랍니다.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jTextArea1.setCaretPosition(0);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rooibos_logoLabel))))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(homepageLinkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label10)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(rooibos_logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homepageLinkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okButton)
                .addGap(20, 20, 20))
        );

        getRootPane().setDefaultButton(okButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void homepageLinkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageLinkLabelMouseClicked
        String str="http://www.teasofts.com";
                //homepageLinkLabel.getText();
      //  System.out.println(str);
        //jLa"http://www.teasofts.com";
        openWebpage(str);
    }//GEN-LAST:event_homepageLinkLabelMouseClicked
      public  void openWebpage(String uristr) {
       URI url = null;
        try {
            url = new URI(uristr);
        } catch (URISyntaxException ex) {
            Logger.getLogger(AboutDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (Desktop.isDesktopSupported()) {
            try {
                // Windows
                Desktop.getDesktop().browse(url);
            } catch (IOException ex) {
                Logger.getLogger(AboutDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            // Ubuntu
            Runtime runtime = Runtime.getRuntime();
            try {
                runtime.exec("/usr/bin/firefox -new-window " + url);
            } catch (IOException ex) {
                Logger.getLogger(AboutDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel homepageLinkLabel;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel label10;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel rooibos_logoLabel;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
