/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.Box;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;

/**
 *
 * @author Administrator
 */
public class GroupSelection extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    private int returnStatus = RET_CANCEL;
    private int start;
    private int end;
    private int group;
    private String[] selectedValues;

    public GroupSelection(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        start = 1;
        end = 20;
        group = 1;
        this.selectedValues = new String[end + 1];
        Arrays.fill(selectedValues, "A");

        initComponents();
        this.setTitle("Group Setting for Subjects");
        // Close the dialog when Esc is pressed

        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    public GroupSelection(java.awt.Frame parent, boolean modal, int start, int end, int group,  String[] selectedValues, Component c) {
        super(parent, modal);
        this.setTitle("Group Setting for Subjects");
        this.setLocationRelativeTo(c);
        this.start = start;
        this.end = end;
        this.group = group;
        if(selectedValues==null){
// System.out.println("GroupSelection class \t end="+end+"\t selectedValues"+selectedValues);
            this.selectedValues = new String[end + 1];
            Arrays.fill(this.selectedValues, "A");
             // System.out.println("GroupSelection class \t end="+end+"\t selectedValues"+selectedValues);

        }
        else  this.selectedValues =selectedValues;
  // System.out.println("GroupSelection class \t end="+end+"\t this.selectedValues size="+this.selectedValues.length);
        initComponents();
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });

    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;//1==ok(saved) //0==cancel
    }

    public String[] getSelectedValues() {
        return selectedValues;
    }

    public int getGroupNum() {
        return group;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containPan = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        myRadioPanel1 = new MyRadioPanel(start,end,group,selectedValues);
        footPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setFocusCycleRoot(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        containPan.setBackground(new java.awt.Color(204, 255, 204));
        containPan.setLayout(new java.awt.BorderLayout());

        topPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));

        jLabel1.setText("Group    ");
        topPanel.add(jLabel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox1.setSelectedItem(""+this.group);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        topPanel.add(jComboBox1);

        containPan.add(topPanel, java.awt.BorderLayout.PAGE_START);
        containPan.add(myRadioPanel1, java.awt.BorderLayout.CENTER);

        footPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        footPanel.add(Box.createHorizontalGlue());
        getRootPane().setDefaultButton(okButton);
        footPanel.add(okButton);
        footPanel.add(Box.createRigidArea(new Dimension(20,0)));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        footPanel.add(cancelButton);

        containPan.add(footPanel, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containPan, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containPan, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.start = myRadioPanel1.getStart();
        this.end = myRadioPanel1.getEnd();

        this.group = Integer.parseInt((String) jComboBox1.getSelectedItem());
        this.selectedValues = myRadioPanel1.getSelectedValues();

        if (!isSelectedAll()) {
            String s="그룹을 모두 선택하여 주십시오";
            Rooibos.setErrorMessage(s);
        }
        else {
            Rooibos.setErrorMessage("");
            doClose(RET_OK);
        }

        // else {
             //JOptionPane.showMessageDialog(this, "그룹을 모두 선택하여주십시오.", "Error", JOptionPane.ERROR_MESSAGE);
        //  }
        // this.selectedValues = myRadioPanel1.getSelectedValues();      
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
        repaint(start, end, group);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        containPan.remove(myRadioPanel1);
        int groupTmp = Integer.parseInt((String) jComboBox1.getSelectedItem());
        repaint(groupTmp);

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }


    private void repaint(int groupNum) {

        containPan.remove(myRadioPanel1);
        myRadioPanel1 = new MyRadioPanel(start, end, groupNum, selectedValues);
        containPan.add(myRadioPanel1);
        containPan.revalidate();
        containPan.repaint();
    }

    public void repaint(int start, int end, int groupNum) {

        this.start = start;
        this.end = end;
          this.group=groupNum;
        containPan.remove(myRadioPanel1);
        jComboBox1.setSelectedItem("" + this.group);
        myRadioPanel1 = new MyRadioPanel(start, end, groupNum, selectedValues);
        containPan.add(myRadioPanel1);
        containPan.revalidate();
        containPan.repaint();
    }
    public void repaint(int start, int end, int groupNum, String[] selectedValue) {

        this.start = start;
        this.end = end;
        this.group=groupNum;
        containPan.remove(myRadioPanel1);
        jComboBox1.setSelectedItem("" + this.group);
        myRadioPanel1 = new MyRadioPanel(start, end, groupNum, selectedValue);
        containPan.add(myRadioPanel1);
        containPan.revalidate();
        containPan.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GroupSelection dialog = new GroupSelection(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel containPan;
    private javax.swing.JPanel footPanel;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private MyRadioPanel myRadioPanel1;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

    private boolean isSelectedAll() {

        for (int i = start; i < end; i++) {
            if (this.selectedValues[i] == null) //myRadioPanel1.setF.setCursor();
            {
                return false;
            }
        }

        return true;
    }

}
